---
ID: "0d372af8-6d1a-4f3e-9f10-bc8bdb96dfc6"
Parent: "8c55b3d8-c365-4a8b-893d-cc095b26561c"
Template: "2384d4b8-396e-4d6d-861c-9fc171659644"
Path: /sitecore/content/Habitat Sites/Habitat Home/home/coveosearchse/CoveoSearchSE Parameters/CoveoSearchSE Parameters Result Templates/Product List Template
DB: master
SharedFields:
- ID: "49ff2392-7514-405a-93c2-838da019131c"
  Hint: Conditions
  Value: _template=225f8638261148419b8919a5440a1da1
- ID: "5a29f470-49e9-4e25-9746-c21b0f917909"
  Hint: ResultLayout
  Value: List
- ID: "d48ad7e5-fd34-4ec2-b753-4e1867b05714"
  Hint: ItemId
  Value: coveoc8bfc116
- ID: "f063331b-6d08-43ae-b32d-b680d2610c95"
  Hint: TemplateName
  Value: productlist
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181002T184957Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\CoveoAdmin
