---
ID: "61848325-c57d-41ce-99a8-3e6cbd308bc1"
Parent: "32682ce9-1da9-44a4-9123-2edebba67c78"
Template: "5787604f-f0b7-412f-a3b3-9e2ee3a67038"
Path: /sitecore/content/Habitat Sites/Habitat Home/home/coveosearchse/CoveoSearchSE Parameters/CoveoSearchSE Parameters Results List/Product Recommendation Card Results List
DB: master
SharedFields:
- ID: "c1469571-d958-4250-8ed0-3f96f3f17f30"
  Hint: ResultsLayout
  Value: "{C8AF1B72-A671-4761-87E4-6308F1299916}"
- ID: "d48ad7e5-fd34-4ec2-b753-4e1867b05714"
  Hint: ItemId
  Value: coveo4a23382f
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181004T212546Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\CoveoAdmin
